services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - expenses-tracker
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started
